package modelos;
// Generated 11-nov-2018 17:52:52 by Hibernate Tools 4.3.1



/**
 * Actividades generated by hbm2java
 */
public class Actividades  implements java.io.Serializable {


     private int idActividad;
     private Etapas etapas;
     private String nombreActi;
     private String descripcionActi;
     private String estadoActi;

    public Actividades() {
    }

	
    public Actividades(int idActividad) {
        this.idActividad = idActividad;
    }
    public Actividades(int idActividad, Etapas etapas, String nombreActi, String descripcionActi, String estadoActi) {
       this.idActividad = idActividad;
       this.etapas = etapas;
       this.nombreActi = nombreActi;
       this.descripcionActi = descripcionActi;
       this.estadoActi = estadoActi;
    }
   
    public int getIdActividad() {
        return this.idActividad;
    }
    
    public void setIdActividad(int idActividad) {
        this.idActividad = idActividad;
    }
    public Etapas getEtapas() {
        return this.etapas;
    }
    
    public void setEtapas(Etapas etapas) {
        this.etapas = etapas;
    }
    public String getNombreActi() {
        return this.nombreActi;
    }
    
    public void setNombreActi(String nombreActi) {
        this.nombreActi = nombreActi;
    }
    public String getDescripcionActi() {
        return this.descripcionActi;
    }
    
    public void setDescripcionActi(String descripcionActi) {
        this.descripcionActi = descripcionActi;
    }
    public String getEstadoActi() {
        return this.estadoActi;
    }
    
    public void setEstadoActi(String estadoActi) {
        this.estadoActi = estadoActi;
    }




}


