package modelos;
// Generated 18-nov-2018 21:13:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int idDepartamento;
     private String nombreDept;
     private Set<Municipio> municipios = new HashSet<Municipio>(0);

    public Departamento() {
    }

	
    public Departamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public Departamento(int idDepartamento, String nombreDept, Set<Municipio> municipios) {
       this.idDepartamento = idDepartamento;
       this.nombreDept = nombreDept;
       this.municipios = municipios;
    }
   
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getNombreDept() {
        return this.nombreDept;
    }
    
    public void setNombreDept(String nombreDept) {
        this.nombreDept = nombreDept;
    }
    public Set<Municipio> getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Set<Municipio> municipios) {
        this.municipios = municipios;
    }




}


