package modelos;
// Generated 11-nov-2018 17:52:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Encargado generated by hbm2java
 */
public class Encargado  implements java.io.Serializable {


     private int idEncargado;
     private Asociacion asociacion;
     private Municipio municipio;
     private Persona persona;
     private String puesto;
     private String telefono;
     private Set<Proyecto> proyectos = new HashSet<Proyecto>(0);

    public Encargado() {
    }

	
    public Encargado(int idEncargado) {
        this.idEncargado = idEncargado;
    }
    public Encargado(int idEncargado, Asociacion asociacion, Municipio municipio, Persona persona, String puesto, String telefono, Set<Proyecto> proyectos) {
       this.idEncargado = idEncargado;
       this.asociacion = asociacion;
       this.municipio = municipio;
       this.persona = persona;
       this.puesto = puesto;
       this.telefono = telefono;
       this.proyectos = proyectos;
    }
   
    public int getIdEncargado() {
        return this.idEncargado;
    }
    
    public void setIdEncargado(int idEncargado) {
        this.idEncargado = idEncargado;
    }
    public Asociacion getAsociacion() {
        return this.asociacion;
    }
    
    public void setAsociacion(Asociacion asociacion) {
        this.asociacion = asociacion;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set<Proyecto> getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set<Proyecto> proyectos) {
        this.proyectos = proyectos;
    }




}


