package modelos;
// Generated 18-nov-2018 21:13:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Genero generated by hbm2java
 */
public class Genero  implements java.io.Serializable {


     private int idGenero;
     private String sexo;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public Genero() {
    }

	
    public Genero(int idGenero) {
        this.idGenero = idGenero;
    }
    public Genero(int idGenero, String sexo, Set<Persona> personas) {
       this.idGenero = idGenero;
       this.sexo = sexo;
       this.personas = personas;
    }
   
    public int getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(int idGenero) {
        this.idGenero = idGenero;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


