package modelos;
// Generated 11-nov-2018 17:52:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private int idProyecto;
     private Encargado encargado;
     private String nombrePry;
     private String descripPry;
     private Long inversion;
     private Integer duracion;
     private Date fechaInicioPry;
     private String estado;
     private Boolean activo;
     private Set<Etapas> etapases = new HashSet<Etapas>(0);

    public Proyecto() {
    }

	
    public Proyecto(int idProyecto) {
        this.idProyecto = idProyecto;
    }
    public Proyecto(int idProyecto, Encargado encargado, String nombrePry, String descripPry, Long inversion, Integer duracion, Date fechaInicioPry, String estado, Boolean activo, Set<Etapas> etapases) {
       this.idProyecto = idProyecto;
       this.encargado = encargado;
       this.nombrePry = nombrePry;
       this.descripPry = descripPry;
       this.inversion = inversion;
       this.duracion = duracion;
       this.fechaInicioPry = fechaInicioPry;
       this.estado = estado;
       this.activo = activo;
       this.etapases = etapases;
    }
   
    public int getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(int idProyecto) {
        this.idProyecto = idProyecto;
    }
    public Encargado getEncargado() {
        return this.encargado;
    }
    
    public void setEncargado(Encargado encargado) {
        this.encargado = encargado;
    }
    public String getNombrePry() {
        return this.nombrePry;
    }
    
    public void setNombrePry(String nombrePry) {
        this.nombrePry = nombrePry;
    }
    public String getDescripPry() {
        return this.descripPry;
    }
    
    public void setDescripPry(String descripPry) {
        this.descripPry = descripPry;
    }
    public Long getInversion() {
        return this.inversion;
    }
    
    public void setInversion(Long inversion) {
        this.inversion = inversion;
    }
    public Integer getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Integer duracion) {
        this.duracion = duracion;
    }
    public Date getFechaInicioPry() {
        return this.fechaInicioPry;
    }
    
    public void setFechaInicioPry(Date fechaInicioPry) {
        this.fechaInicioPry = fechaInicioPry;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public Set<Etapas> getEtapases() {
        return this.etapases;
    }
    
    public void setEtapases(Set<Etapas> etapases) {
        this.etapases = etapases;
    }




}


